openapi: 3.0.0
info:
  title: kytos/topology
  version: 0.0.1
  description: Manage the network topology.
paths:
  /api/kytos/topology/devices:
    get:
      summary: Return a json with all the devices in the topology.
      description: Responsible for the /api/kytos/topology/devices endpoint. e.g. [<list of devices>] Returns: string: json with all the devices in the topology
      parameters:  # If you have parameters in the URL
        - name: Parameter's name as in path.
          required: true
          description: Describe parameter here
          in: path
      responses:
        200:  # You can add more responses
          description: Describe a successful call.
          content:
            application/json:  # You can also use text/plain, for example
              schema:
                type: object  # Adapt to your response
                properties:
                  prop_one:
                    type: string
                    description: Meaning of prop_one
                    example: an example of prop_one
                  second_prop:
                    type: integer
                    description: Meaning of second_prop
                    example: 42
  /api/kytos/topology/links:
    get:
      summary: Return a json with all the links in the topology.
      description: Responsible for the /api/kytos/topology/links endpoint. Returns: string: json with all the links in the topology.
      parameters:  # If you have parameters in the URL
        - name: Parameter's name as in path.
          required: true
          description: Describe parameter here
          in: path
      responses:
        200:  # You can add more responses
          description: Describe a successful call.
          content:
            application/json:  # You can also use text/plain, for example
              schema:
                type: object  # Adapt to your response
                properties:
                  prop_one:
                    type: string
                    description: Meaning of prop_one
                    example: an example of prop_one
                  second_prop:
                    type: integer
                    description: Meaning of second_prop
                    example: 42
