# This is a basic workflow to help you get started with Actions

name: Copy OpenAPI to GitHub Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  copy-file:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Pushes openapi.yml
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        with:
          source_file: 'openapi.yml'
          destination_repo: 'kytos-ng/kytos-ng.github.io'
          destination_folder: 'topology'
          destination_branch: 'master'
          commit_message: 'Pushing topology openapi.yml'
